const Types = {
    ENTRIES_LOADING: "ENTRIES_LOADING",
    CATEGORIES_LOADING: "CATEGORIES_LOADING",
    GET_ENTRIES:"GET_ENTRIES",
    GET_CATEGORIES:"GET_CATEGORIES",
    DELETE_ENTRY:"DELETE_ENTRY",
    DELETE_CATEGORY:"DELETE_CATEGORY",
    CREATE_ENTRY:"CREATE_ENTRY",
    CREATE_CATEGORY:"CREATE_CATEGORY"
};

export default Types
